//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESRD_Sample01
{
    using System;
    using System.Collections.Generic;
    
    public partial class SampleMaster
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SampleMaster()
        {
            this.SampleDetail = new HashSet<SampleDetail>();
            this.TypeOfSample = new HashSet<TypeOfSample>();
        }
    
        public int Id { get; set; }
        public string Used { get; set; }
        public string Temp { get; set; }
        public string Uncertainty { get; set; }
        public string Container { get; set; }
        public Nullable<int> ContactPersonId { get; set; }
    
        public virtual ContactPerson ContactPerson { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SampleDetail> SampleDetail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TypeOfSample> TypeOfSample { get; set; }
    }
}
