//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESRD_Sample01
{
    using System;
    using System.Collections.Generic;
    
    public partial class SampleDetail
    {
        public int Id { get; set; }
        public Nullable<int> No { get; set; }
        public string SampleCodeNames { get; set; }
        public string QuantityPerContainer { get; set; }
        public string TotalContainer { get; set; }
        public string ParameterTested { get; set; }
        public string UnitOfTesting { get; set; }
        public string LabNo { get; set; }
        public string SampleCondition { get; set; }
        public Nullable<int> Price { get; set; }
        public Nullable<int> TypeOfSampleDetailId { get; set; }
        public Nullable<int> SampleMasterId { get; set; }
    
        public virtual SampleMaster SampleMaster { get; set; }
        public virtual TypeOfSampleDetail TypeOfSampleDetail { get; set; }
    }
}
