//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESRD_Sample01
{
    using System;
    using System.Collections.Generic;
    
    public partial class TypeOfSample
    {
        public int Id { get; set; }
        public string ChemicalFertilizer { get; set; }
        public string OrganicFertilizer { get; set; }
        public string ChemicalOrganicFertilizer { get; set; }
        public string Water { get; set; }
        public string Soil { get; set; }
        public string Ethanol { get; set; }
        public string Other { get; set; }
        public Nullable<int> SampleMasterId { get; set; }
    
        public virtual SampleMaster SampleMaster { get; set; }
    }
}
