//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESRD_Sample01
{
    using System;
    using System.Collections.Generic;
    
    public partial class TypeOfSampleDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TypeOfSampleDetail()
        {
            this.SampleDetail = new HashSet<SampleDetail>();
        }
    
        public int Id { get; set; }
        public string TypeOfSampleDetailName { get; set; }
        public Nullable<int> TypeOfSampleId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SampleDetail> SampleDetail { get; set; }
    }
}
